//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTuc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TinTucEntities : DbContext
    {
        public TinTucEntities()
            : base("name=TinTucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<BaiViet_5New_Result> BaiViet_5New()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaiViet_5New_Result>("BaiViet_5New");
        }
    
        public virtual ObjectResult<BaiViet_ByIdCategories_Result> BaiViet_ByIdCategories(Nullable<int> iD_DM)
        {
            var iD_DMParameter = iD_DM.HasValue ?
                new ObjectParameter("ID_DM", iD_DM) :
                new ObjectParameter("ID_DM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaiViet_ByIdCategories_Result>("BaiViet_ByIdCategories", iD_DMParameter);
        }
    
        public virtual ObjectResult<BaiViet_ByIdPost_Result> BaiViet_ByIdPost(Nullable<int> iD_BV)
        {
            var iD_BVParameter = iD_BV.HasValue ?
                new ObjectParameter("ID_BV", iD_BV) :
                new ObjectParameter("ID_BV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaiViet_ByIdPost_Result>("BaiViet_ByIdPost", iD_BVParameter);
        }
    
        public virtual ObjectResult<BaiViet_SelectAll_Result> BaiViet_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaiViet_SelectAll_Result>("BaiViet_SelectAll");
        }
    
        public virtual ObjectResult<BinhLuan_ByIdPost_Result> BinhLuan_ByIdPost(Nullable<int> iD_BV)
        {
            var iD_BVParameter = iD_BV.HasValue ?
                new ObjectParameter("ID_BV", iD_BV) :
                new ObjectParameter("ID_BV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BinhLuan_ByIdPost_Result>("BinhLuan_ByIdPost", iD_BVParameter);
        }
    
        public virtual ObjectResult<BinhLuan_SelectByID_Result> BinhLuan_SelectByID(Nullable<int> iD_BV)
        {
            var iD_BVParameter = iD_BV.HasValue ?
                new ObjectParameter("ID_BV", iD_BV) :
                new ObjectParameter("ID_BV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BinhLuan_SelectByID_Result>("BinhLuan_SelectByID", iD_BVParameter);
        }
    
        public virtual ObjectResult<DanhMuc_ByIdCategories_Result> DanhMuc_ByIdCategories(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhMuc_ByIdCategories_Result>("DanhMuc_ByIdCategories", iDParameter);
        }
    
        public virtual ObjectResult<DanhMuc_SelectAll_Result> DanhMuc_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhMuc_SelectAll_Result>("DanhMuc_SelectAll");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
